// Novice — CPR-AI Coach
// GNU General Public License v3.0
// Copyright (C) 2024 Jean Robert Gatwaza — African Leadership University
//
// TTS service — cross-platform voice coaching.
//
// Language tiers:
//   EN: flutter_tts (offline on mobile, Web Speech API on web)
//   RW: 1. Umuganda TTS HTTP (if endpoint configured in .env)
//       2. flutter_tts English fallback
//
// TODO: Record native Kinyarwanda speaker for assets/audio/rw/
// TODO: Set UMUGANDA_TTS_URL in .env before enabling RW HTTP tier

import 'package:flutter_tts/flutter_tts.dart';
import 'package:http/http.dart' as http;
import 'package:logger/logger.dart';

import '../core/constants/app_constants.dart';

// TODO (Phase 2): Uncomment when audioplayers is added to pubspec.yaml
// import 'package:audioplayers/audioplayers.dart';

class TtsService {
  TtsService({this.umugandaTtsUrl});

  final String? umugandaTtsUrl;
  final _tts = FlutterTts();
  final _log = Logger();

  // TODO (Phase 2): final _player = AudioPlayer();

  bool _initialized = false;
  bool _isSpeaking  = false;
  String _lang      = 'en';

  Future<void> init() async {
    await _tts.setLanguage('en-US');
    await _tts.setSpeechRate(0.9);
    await _tts.setVolume(1.0);
    await _tts.setPitch(1.0);

    _tts.setStartHandler(()    => _isSpeaking = true);
    _tts.setCompletionHandler(()=> _isSpeaking = false);
    _tts.setErrorHandler((msg) {
      _log.w('TtsService: $msg');
      _isSpeaking = false;
    });

    _initialized = true;
    _log.i('TtsService: initialized');
  }

  void setLanguage(String lang) => _lang = lang;

  Future<void> speakKey(String key) async {
    final prompts = _lang == 'rw'
        ? AppConstants.promptsRw
        : AppConstants.promptsEn;
    final message = prompts[key] ?? prompts['good']!;
    await speak(message, key: key);
  }

  /// [key] is used to look up a pre-baked WAV file for Kinyarwanda.
  /// Pass null to always use TTS synthesis.
  ///
  /// FIX: this used to call `await stop()` before every utterance whenever
  /// something was already speaking. On the Web Speech API, cancelling an
  /// in-progress utterance fires an `error` event with reason
  /// "interrupted" — so any time feedback changed while a prompt was still
  /// being read (which was happening almost every frame before the web
  /// wrist-velocity-units fix), the coach would get cut off mid-sentence
  /// and spam the log with SpeechSynthesisErrorEvent/"interrupted" entries.
  /// FeedbackEngine.shouldSpeak() already rate-limits how often a prompt is
  /// allowed through (voiceCoachingCooldownMs, critical prompts bypass it),
  /// so it's safe — and far less jarring — to just skip a new non-critical
  /// prompt if the coach is mid-sentence rather than barge in over it.
  Future<void> speak(String message, {String? key}) async {
    if (!_initialized) await init();
    if (_isSpeaking) {
      _log.i('TtsService: still speaking, skipping overlapping prompt');
      return;
    }

    if (_lang == 'rw') {
      await _speakKinyarwanda(message, key: key);
    } else {
      await _speakEnglish(message);
    }
  }

  Future<void> stop() async {
    await _tts.stop();
    _isSpeaking = false;
  }

  Future<void> dispose() async => _tts.stop();

  Future<void> _speakEnglish(String message) async {
    await _tts.setLanguage('en-US');
    await _tts.speak(message);
  }

  Future<void> _speakKinyarwanda(String message, {String? key}) async {
    // ── Tier 1: Pre-baked WAV asset ────────────────────────────────────────
    // Generated by: ml_pipeline/src/tts/prebake_audio.py
    // Stored at:    assets/audio/rw/<key>.wav
    // This is the recommended approach for pilot study (fully offline, consistent latency).
    //
    // TODO (Phase 2): Uncomment when audioplayers is added to pubspec.yaml
    //   and prebake_audio.py has been run to generate the files.
    //
    // if (key != null) {
    //   try {
    //     await _player.play(AssetSource('audio/rw/$key.wav'));
    //     _isSpeaking = true;
    //     return;
    //   } catch (e) {
    //     _log.w('TtsService: pre-baked WAV not found for key "$key": $e');
    //   }
    // }

    // ── Tier 2: Umuganda TTS HTTP server ─────────────────────────────────
    // Started by: ml_pipeline/src/tts/kinyarwanda_tts_server.py
    // Configured via UMUGANDA_TTS_URL in .env
    if (umugandaTtsUrl != null && umugandaTtsUrl!.isNotEmpty) {
      final ok = await _umugandaHttp(message);
      if (ok) return;
    }

    // ── Tier 3: English fallback ──────────────────────────────────────────
    _log.w('TtsService: Kinyarwanda TTS unavailable — falling back to English');
    await _speakEnglish(message);
  }

  Future<bool> _umugandaHttp(String message) async {
    try {
      final response = await http.post(
        Uri.parse('$umugandaTtsUrl/tts'),
        headers: {'Content-Type': 'application/json'},
        body: '{"text":"${message.replaceAll('"', '\\"')}","lang":"rw"}',
      ).timeout(const Duration(seconds: 3));

      if (response.statusCode == 200) {
        // TODO (Phase 2): Play WAV bytes from response.bodyBytes
        // final bytes = response.bodyBytes;
        // await _player.play(BytesSource(bytes));
        // _isSpeaking = true;
        _log.i('TtsService: Umuganda HTTP ${response.statusCode}');
        return false; // false until audioplayers wired
      }
      return false;
    } catch (e) {
      _log.w('TtsService: Umuganda HTTP failed — $e');
      return false;
    }
  }
}
